const	ROUTE_OPT_SHORTEST = 0; // 최단거리
const	ROUTE_OPT_RECOMMENDED = 1; // 추천
const	ROUTE_OPT_COMFORTABLE = 2; // 편안한
const	ROUTE_OPT_FASTEST = 3; // 최소시간
const	ROUTE_OPT_MAINROAD = 4; // 큰길
const	ROUTE_OPT_PEDESTRIAN = 5; // 보행자 전용
const	ROUTE_OPT_TRAIL = 6; // 둘레길 전용
const	ROUTE_OPT_BIKE = 7; // 자전거 전용
const	ROUTE_OPT_AUTOMATION = 8; // 자율주행 전용

const	ROUTE_AVOID_NONE = 0;
	//ROUTE_AVOID_HIKING = 1, // 등산로
	//ROUTE_AVOID_TRAIL = 2, // 둘레길
	//ROUTE_AVOID_BIKE = 4, // 자전거
	//ROUTE_AVOID_CROSS = 8, // 종주길

const	ROUTE_AVOID_ALLEY = 1;
const	ROUTE_AVOID_PAVE = 2;
const	ROUTE_AVOID_STAIRS = 4;
const	ROUTE_AVOID_BRIDGE = 8;
const	ROUTE_AVOID_ROCK = 16;
const	ROUTE_AVOID_RIDGE = 32;
const	ROUTE_AVOID_LADDER = 64;
const	ROUTE_AVOID_ROPE = 128;
const	ROUTE_AVOID_TATTERED = 256;
const	ROUTE_AVOID_PALM = 512;
const	ROUTE_AVOID_DECK = 1024;


module.exports = {
    // option
    ROUTE_OPT_SHORTEST, ROUTE_OPT_RECOMMENDED, ROUTE_OPT_COMFORTABLE, ROUTE_OPT_FASTEST, ROUTE_OPT_MAINROAD, 
    ROUTE_OPT_PEDESTRIAN, ROUTE_OPT_TRAIL, ROUTE_OPT_BIKE, ROUTE_OPT_AUTOMATION, 

    // avoid
    ROUTE_AVOID_NONE, ROUTE_AVOID_ALLEY, ROUTE_AVOID_PAVE, ROUTE_AVOID_STAIRS, ROUTE_AVOID_BRIDGE,
    ROUTE_AVOID_ROCK, ROUTE_AVOID_RIDGE, ROUTE_AVOID_LADDER, ROUTE_AVOID_ROPE, ROUTE_AVOID_TATTERED, 
    ROUTE_AVOID_PALM, ROUTE_AVOID_DECK,
}